(setq inhibit-splash-screen t)
(set-scroll-bar-mode 'right)
(setq make-backup-files nil)
(setq compile-comand "opmake")
(setq scroll-step 1)
(setq mouse-wheel-progressive-speed nil)
(setq transient-mark-mode 0)
(tool-bar-mode -1)
(require 'color-theme)
(color-theme-initialize)
(color-theme-charcoal-black)
(setq tab-width 4)
(setq-default indent-tabs-mode 1)
(add-hook 'python-mode-hook
  (lambda ()
    (setq indent-tabs-mode t)
	(setq python-indent 4)
	(setq tab-width 4)))
(require 'tramp)
(setq tramp-default-method "scp")